import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider} from '@clerk/nextjs'
// app/[chatID]/layout.tsx
import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import React from 'react'
import { getUserChats } from "@/app/actions";
import "./globals.css";
import { DeleteChatsWrapper } from "@/components/DeleteChatsWraper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log('signed in, top level session', session);

  if (!session.userId) {
    return redirect("/sign-in");
  }

  const userChats = await getUserChats(session.userId);
  console.log('userChats', userChats);
  return (
    <ClerkProvider>
    <html lang="en">
      <head>
      <script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      <DeleteChatsWrapper userChats={userChats} userID={session.userId} />

      </body>
    </html>
    </ClerkProvider>
  );
}
